# Generated by Django 4.0 on 2022-07-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myadmin', '0003_danhsachtintuc_trangthai_alter_danhsachtintuc_mieuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='baiviet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('mieuta', models.CharField(blank=True, max_length=4096, null=True)),
                ('noidung', models.CharField(blank=True, max_length=20096, null=True)),
                ('trangthai', models.BooleanField(blank=True, default=True)),
                ('ngaytao', models.DateTimeField(blank=True, null=True)),
                ('danhsachtintuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmtt', to='myadmin.danhsachtintuc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
